# Generated by Django 2.1 on 2018-08-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=2)),
                ('father_name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField(max_length=11)),
            ],
        ),
    ]
